# Generated by Django 3.0.6 on 2020-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.BooleanField()),
                ('m2', models.BooleanField()),
                ('pwm', models.IntegerField()),
            ],
        ),
    ]
