# Generated by Django 3.0.6 on 2020-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='d1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motor',
            name='d2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motor',
            name='m1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motor',
            name='m2',
            field=models.BooleanField(default=False),
        ),
    ]
