# Generated by Django 3.0.6 on 2020-06-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200617_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='motor_devri',
            new_name='deniz_seviyesi',
        ),
    ]
