# Generated by Django 3.0.6 on 2020-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200617_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='basinc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='deniz_seviyesi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='derinlik',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sicaklik',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
